// Display and input contracts only. Execution workflows remain on Agent1000.
export const AGENT_CATALOG = [
  {
    code: "academy-journal",
    name: "수업일지",
    description: "선생님 메모로 학부모가 읽을 수업일지를 씁니다.",
    group: "학원 특화",
    priority: true,
    available: true,
    fields: [
      {
        key: "student_name",
        label: "학생명",
        type: "text",
        required: true,
        placeholder: "김도윤",
      },
      {
        key: "class_name",
        label: "반 이름",
        type: "text",
        placeholder: "중2 수학 A반",
      },
      {
        key: "lesson_date",
        label: "수업일",
        type: "date",
      },
      {
        key: "teacher_notes",
        label: "선생님 메모",
        type: "textarea",
        required: true,
        placeholder:
          "이차함수 그래프. 꼭짓점은 잡는데 평행이동에서 부호를 놓침.",
      },
      {
        key: "homework",
        label: "숙제(선택)",
        type: "text",
        placeholder: "교재 82~85쪽",
      },
      {
        key: "materials",
        label: "교재·자료(선택)",
        type: "text",
        placeholder: "쎈 수학 상",
      },
      {
        key: "next_class_date",
        label: "다음 수업일(선택)",
        type: "date",
      },
    ],
  },
  {
    code: "academy-ledger",
    name: "진도·출결 장부",
    description: "출결·진도·성적을 한 장으로 정리해 학부모에게 보여 줍니다.",
    group: "학원 특화",
    priority: true,
    available: true,
    fields: [
      {
        key: "student_name",
        label: "학생명",
        type: "text",
        required: true,
        placeholder: "김도윤",
      },
      {
        key: "class_name",
        label: "반 이름",
        type: "text",
        placeholder: "중2 수학 A반",
      },
      {
        key: "today",
        label: "기준일(오늘)",
        type: "date",
      },
      {
        key: "total_units",
        label: "전체 진도 수(선택)",
        type: "number",
        placeholder: "24",
      },
      {
        key: "attendance",
        label: "출결 (날짜 | 출석·결석·지각·보강)",
        type: "list",
        subKeys: ["date", "status"],
        placeholder: "2026-08-01 | 출석\n2026-08-04 | 지각",
      },
      {
        key: "progress",
        label: "진도 (날짜 | 단원 | 메모)",
        type: "list",
        subKeys: ["date", "unit", "note"],
        placeholder: "2026-08-01 | 이차함수 | 그래프 이동",
      },
      {
        key: "scores",
        label: "성적 (날짜 | 시험명 | 점수 | 만점)",
        type: "list",
        subKeys: ["date", "name", "score", "max"],
        placeholder: "2026-08-05 | 단원평가 | 82 | 100",
      },
      {
        key: "teacher_comment",
        label: "선생님 총평(선택)",
        type: "textarea",
        placeholder: "계산 실수만 줄이면 다음 단원도 무리 없습니다.",
      },
    ],
  },
  {
    code: "academy-reenroll",
    name: "재등록 리마인더",
    description: "수강 기간과 남은 횟수만으로 재등록 안내문을 준비합니다.",
    group: "학원 특화",
    priority: true,
    available: true,
    fields: [
      {
        key: "student_name",
        label: "학생명",
        type: "text",
        required: true,
        placeholder: "김도윤",
      },
      {
        key: "class_name",
        label: "반 이름",
        type: "text",
        placeholder: "중2 수학 A반",
      },
      {
        key: "today",
        label: "기준일(오늘)",
        type: "date",
      },
      {
        key: "term_end_date",
        label: "수강 종료일",
        type: "date",
      },
      {
        key: "sessions_total",
        label: "총 횟수(선택)",
        type: "number",
        placeholder: "24",
      },
      {
        key: "sessions_used",
        label: "사용 횟수(선택)",
        type: "number",
        placeholder: "19",
      },
      {
        key: "tuition_krw",
        label: "수강료(원, 선택)",
        type: "number",
        placeholder: "320000",
      },
      {
        key: "discount_note",
        label: "할인 안내(선택)",
        type: "text",
        placeholder: "형제 등록 시 10%",
      },
      {
        key: "next_term_start",
        label: "다음 기수 시작일(선택)",
        type: "date",
      },
      {
        key: "notice_window_days",
        label: "안내 시작 시점(일 전 · 기본 30)",
        type: "number",
        placeholder: "30",
      },
    ],
  },
  {
    code: "academy-inquiry",
    name: "문의 답변",
    description:
      "학원이 알려 준 범위 안에서만 학부모 문의에 답장 초안을 씁니다.",
    group: "학원 특화",
    priority: true,
    available: true,
    fields: [
      {
        key: "academy_name",
        label: "학원명",
        type: "text",
        placeholder: "온수학학원",
      },
      {
        key: "parent_name",
        label: "학부모님 성함(선택)",
        type: "text",
        placeholder: "김민지",
      },
      {
        key: "inquiry",
        label: "받은 문의 글",
        type: "textarea",
        required: true,
        placeholder: "중2 수학반 시간표랑 수강료 알 수 있을까요?",
      },
      {
        key: "tuition_krw",
        label: "수강료(원, 선택)",
        type: "number",
        placeholder: "320000",
      },
      {
        key: "tuition_note",
        label: "수강료 안내(선택)",
        type: "textarea",
        placeholder: "주 2회 월 32만원, 교재비 별도",
      },
      {
        key: "schedule_note",
        label: "시간표 안내(선택)",
        type: "textarea",
        placeholder: "중2 수학 월·목 19:00~21:00",
      },
      {
        key: "level_test_note",
        label: "레벨테스트 안내(선택)",
        type: "textarea",
        placeholder: "매주 토 10시, 예약제",
      },
      {
        key: "class_note",
        label: "반 편성 안내(선택)",
        type: "textarea",
        placeholder: "한 반 최대 8명",
      },
      {
        key: "curriculum_note",
        label: "커리큘럼 안내(선택)",
        type: "textarea",
        placeholder: "학기 중 내신, 방학 중 선행",
      },
      {
        key: "consult_note",
        label: "상담 안내(선택)",
        type: "textarea",
        placeholder: "평일 14~18시 전화 상담",
      },
      {
        key: "location_note",
        label: "위치·주차 안내(선택)",
        type: "textarea",
        placeholder: "회기역 2번 출구 도보 3분, 주차 불가",
      },
      {
        key: "refund_note",
        label: "환불 규정 안내(선택)",
        type: "textarea",
        placeholder: "학원법 기준 일할 환불",
      },
      {
        key: "shuttle_note",
        label: "셔틀 안내(선택)",
        type: "textarea",
        placeholder: "셔틀은 운행하지 않습니다",
      },
    ],
  },
  {
    code: "academy-briefing",
    name: "우리 아이 브리핑 담당",
    description:
      "답안지 사진을 읽어 학부모께 보낼 주간 브리핑 초안을 만듭니다.",
    group: "학원 특화",
    priority: true,
    available: true,
    fields: [
      {
        key: "photo_url",
        label: "답안지 사진",
        type: "photo",
        required: true,
      },
      {
        key: "student_name",
        label: "학생 이름",
        type: "text",
        placeholder: "김도윤",
      },
      {
        key: "subject",
        label: "과목(선택)",
        type: "text",
        placeholder: "수학",
      },
      {
        key: "week",
        label: "주차(선택)",
        type: "number",
        placeholder: "3",
      },
      {
        key: "kind",
        label: "종류",
        type: "select",
        options: ["exam", "homework"],
      },
      {
        key: "toc",
        label: "이번 단원 목록 (한 줄에 하나)",
        type: "list",
        subKeys: ["name"],
        placeholder: "이차방정식\n이차함수\n피타고라스 정리",
      },
      {
        key: "actions",
        label: "다음 주 액션 목록 (한 줄에 하나)",
        type: "list",
        subKeys: ["name"],
        placeholder: "보충 프린트 제공\n클리닉 시간 안내\n오답 노트 점검",
      },
      {
        key: "teacher_note",
        label: "선생님 메모(선택)",
        type: "textarea",
        placeholder: "계산 실수가 반복됩니다",
      },
    ],
  },
  {
    code: "academy-popup",
    name: "팝업·소식 담당",
    description:
      "기간이 있는 소식을 팝업 문구와 상단 띠, 그리고 채널별 복붙 꾸러미로 만듭니다.",
    group: "학원 특화",
    priority: true,
    available: true,
    fields: [
      {
        key: "offer_text",
        label: "알릴 내용",
        type: "textarea",
        required: true,
        placeholder: "겨울 특강 사전 등록",
      },
      {
        key: "valid_from",
        label: "시작일",
        type: "date",
        required: true,
      },
      {
        key: "valid_until",
        label: "종료일",
        type: "date",
        required: true,
      },
      {
        key: "image_url",
        label: "사진(선택)",
        type: "photo",
      },
    ],
  },
  {
    code: "academy-sns",
    name: "SNS·소식 담당",
    description:
      "사진 한 장과 한 줄 메모로 지면마다 맞춘 글을 만들어 드립니다.",
    group: "학원 특화",
    priority: false,
    available: true,
    fields: [
      {
        key: "owner_note",
        label: "알릴 내용",
        type: "textarea",
        required: true,
        placeholder: "겨울 특강 시간표 나왔습니다",
      },
      {
        key: "photo_url",
        label: "사진(선택)",
        type: "photo",
      },
      {
        key: "shop_name",
        label: "상호(선택)",
        type: "text",
        placeholder: "등용학원",
      },
      {
        key: "dong",
        label: "동네(선택)",
        type: "text",
        placeholder: "회기동",
      },
      {
        key: "format",
        label: "글의 종류",
        type: "select",
        options: ["F1", "F2", "F3", "F4", "F5"],
      },
      {
        key: "surfaces",
        label: "올릴 곳 (비우면 전부)",
        type: "multiselect",
        options: [
          "plaza",
          "website",
          "instagram",
          "naver_blog",
          "naver_place",
          "kakao_channel",
        ],
      },
    ],
  },
  {
    code: "academy-study-ledger",
    name: "학습 장부",
    description:
      "출석·진도·성적을 장부로 정리하고 재등록 안내 시점만 따로 알려 줍니다.",
    group: "학원 특화",
    priority: true,
    available: true,
    fields: [
      {
        key: "student_name",
        label: "학생 이름",
        type: "text",
        required: true,
        placeholder: "이서준",
      },
      {
        key: "class_name",
        label: "반 이름",
        type: "text",
        placeholder: "중2 수학 A반",
      },
      {
        key: "today",
        label: "기준일(오늘)",
        type: "date",
      },
      {
        key: "total_units",
        label: "전체 단원 수(진도율의 분모)",
        type: "number",
        placeholder: "20",
      },
      {
        key: "attendance",
        label: "출석 (날짜 | 상태)",
        type: "list",
        subKeys: ["date", "status"],
        placeholder: "2026-07-03 | 출석\n2026-07-10 | 지각",
      },
      {
        key: "progress",
        label: "진도 (날짜 | 단원 | 메모)",
        type: "list",
        subKeys: ["date", "unit", "note"],
        placeholder: "2026-07-03 | 1단원 유리수 | 완료",
      },
      {
        key: "scores",
        label: "성적 (날짜 | 시험명 | 점수 | 만점)",
        type: "list",
        subKeys: ["date", "name", "score", "max"],
        placeholder: "2026-07-05 | 단원평가1 | 72 | 100",
      },
      {
        key: "teacher_comment",
        label: "선생님 메모(선택)",
        type: "textarea",
        placeholder: "계산 실수가 반복됩니다",
      },
      {
        key: "term_end_date",
        label: "수강 종료일",
        type: "date",
      },
      {
        key: "sessions_total",
        label: "총 수업 회차",
        type: "number",
        placeholder: "20",
      },
      {
        key: "sessions_used",
        label: "지난 회차",
        type: "number",
        placeholder: "16",
      },
      {
        key: "tuition_krw",
        label: "수강료(원 · 선택)",
        type: "number",
        placeholder: "320000",
      },
      {
        key: "discount_note",
        label: "할인 안내(선택 · 여기 적힌 금액만 열립니다)",
        type: "text",
        placeholder: "형제 할인 30,000원",
      },
      {
        key: "next_term_start",
        label: "다음 학기 시작일(선택)",
        type: "date",
      },
      {
        key: "notice_window_days",
        label: "안내 창(일 · 기본 30)",
        type: "number",
        placeholder: "30",
      },
    ],
  },
  {
    code: "academy-career",
    name: "진로 상담 리포트",
    description:
      "학생이 직접 말한 관심·활동·희망만으로 다음 탐색 단계와 질문을 정리합니다.",
    group: "학원 특화",
    priority: true,
    available: true,
    fields: [
      {
        key: "student_alias",
        label: "학생 호칭(실명 말고)",
        type: "text",
        required: true,
        placeholder: "지훈",
      },
      {
        key: "grade_level",
        label: "학년",
        type: "text",
        placeholder: "고1",
      },
      {
        key: "interests",
        label: "학생이 직접 말한 관심 (한 줄에 하나)",
        type: "list",
        subKeys: ["name"],
        placeholder: "컴퓨터로 만드는 것\n게임 기획",
      },
      {
        key: "activities",
        label: "실제로 한 활동 (활동 | 메모)",
        type: "list",
        subKeys: ["name", "note"],
        placeholder:
          "학교 코딩 동아리 | 1학기 동안 주 1회\n교내 대회 | 팀으로 참가",
      },
      {
        key: "wishes",
        label: "학생이 적어 낸 희망 (한 줄에 하나)",
        type: "list",
        subKeys: ["name"],
        placeholder: "컴퓨터공학과",
      },
      {
        key: "counselor_note",
        label: "상담 메모(선택)",
        type: "textarea",
        placeholder: "말수는 적지만 만든 것을 보여 줄 때 눈이 반짝입니다",
      },
      {
        key: "today",
        label: "기준일(오늘)",
        type: "date",
      },
    ],
  },
  {
    code: "academy-place",
    name: "플레이스 담당",
    description:
      "네이버·카카오·구글·당근에 넣을 등록 꾸러미와 대표키워드, 사진 체크리스트를 만듭니다.",
    group: "학원 특화",
    priority: true,
    available: true,
    fields: [
      {
        key: "channel",
        label: "채널",
        type: "select",
        required: true,
        options: ["naver_place", "kakao_map", "google_gbp", "karrot"],
      },
      {
        key: "store.name",
        label: "상호",
        type: "text",
        required: true,
        placeholder: "다온 수학학원",
      },
      {
        key: "store.dong",
        label: "동",
        type: "text",
        placeholder: "회기동",
      },
      {
        key: "store.gu",
        label: "구·시",
        type: "text",
        placeholder: "동대문구",
      },
      {
        key: "store.station",
        label: "가까운 역",
        type: "text",
        placeholder: "회기역",
      },
      {
        key: "store.station_distance_m",
        label: "역에서 거리(m)",
        type: "number",
        placeholder: "220",
      },
      {
        key: "store.address",
        label: "주소",
        type: "text",
        placeholder: "서울 동대문구 회기로 12",
      },
      {
        key: "store.phone",
        label: "전화",
        type: "text",
        placeholder: "02-000-0000",
      },
      {
        key: "store.hours",
        label: "영업시간",
        type: "text",
        placeholder: "10:00-19:00 (월 휴무)",
      },
      {
        key: "store.slug",
        label: "홈페이지 주소(슬러그)",
        type: "text",
        placeholder: "demo-academy",
      },
      {
        key: "store.service_top",
        label: "대표 서비스",
        type: "text",
        placeholder: "중등 수학",
      },
      {
        key: "store.store_type",
        label: "매장 유형",
        type: "text",
        placeholder: "보습학원",
      },
      {
        key: "keywords",
        label: "대표키워드 5개 (비워 두면 매장 정보에서 가져옵니다)",
        type: "taglist",
        placeholder: "회기동학원, 중등수학, 고등수학, 내신대비, 소수정예",
      },
      {
        key: "owner_note",
        label: "사장님 메모(선택)",
        type: "textarea",
        placeholder: "한 반 정원이 여덟 명이에요",
      },
    ],
  },
  {
    code: "academy-place-distribute",
    name: "플레이스 채널 배포",
    description:
      "승인된 글 한 건을 채널별 형식으로 바꿔 복사할 수 있게 만듭니다.",
    group: "학원 특화",
    priority: false,
    available: true,
    fields: [
      {
        key: "channels",
        label: "보낼 채널",
        type: "multiselect",
        options: ["naver_place", "kakao_map", "google_gbp", "karrot"],
      },
      {
        key: "content.title",
        label: "글 제목",
        type: "text",
        required: true,
        placeholder: "2학기 중등반 안내",
      },
      {
        key: "content.body",
        label: "글 본문",
        type: "textarea",
        required: true,
        placeholder: "2학기 진도에 맞춘 중등 수학반을 엽니다.",
      },
      {
        key: "content.format",
        label: "글 형식",
        type: "select",
        options: ["F1", "F2", "F3", "F4", "F5"],
      },
      {
        key: "content.id",
        label: "글 id(선택)",
        type: "text",
      },
      {
        key: "store.name",
        label: "상호",
        type: "text",
        placeholder: "다온 수학학원",
      },
      {
        key: "store.dong",
        label: "동",
        type: "text",
        placeholder: "회기동",
      },
      {
        key: "store.slug",
        label: "홈페이지 주소(슬러그)",
        type: "text",
        placeholder: "demo-academy",
      },
      {
        key: "posted_this_week.naver_place",
        label: "이번 주 게시 수 · 네이버 플레이스",
        type: "number",
      },
      {
        key: "posted_this_week.kakao_map",
        label: "이번 주 게시 수 · 카카오맵",
        type: "number",
      },
      {
        key: "posted_this_week.google_gbp",
        label: "이번 주 게시 수 · 구글",
        type: "number",
      },
      {
        key: "posted_this_week.karrot",
        label: "이번 주 게시 수 · 당근",
        type: "number",
      },
      {
        key: "owner_note",
        label: "사장님 메모(선택)",
        type: "textarea",
      },
    ],
  },
  {
    code: "academy-place-report",
    name: "플레이스 성과 리포트",
    description:
      "채널별 숫자를 모아 무엇을 말할 수 있고 무엇을 말할 수 없는지까지 적어 줍니다.",
    group: "학원 특화",
    priority: false,
    available: true,
    fields: [
      {
        key: "period_from",
        label: "시작일",
        type: "date",
        required: true,
      },
      {
        key: "period_to",
        label: "종료일",
        type: "date",
        required: true,
      },
      {
        key: "metrics",
        label:
          "채널별 지표 (채널 | 노출 | 클릭 | 전화 | 길찾기 | 리뷰수 | 평점 | 출처)",
        type: "list",
        subKeys: [
          "channel",
          "impressions",
          "clicks",
          "calls",
          "direction_requests",
          "review_count",
          "avg_rating",
          "source",
        ],
        placeholder:
          "naver_place | 1200 | 90 | 12 | 30 | 8 | 4.7 | manual\nkakao_map | 400 | 20 | 3 | 9 | 2 | 4.5 | manual",
      },
      {
        key: "prev_metrics",
        label: "지난 기간 지표(선택 · 같은 형식)",
        type: "list",
        subKeys: [
          "channel",
          "impressions",
          "clicks",
          "calls",
          "direction_requests",
          "review_count",
          "avg_rating",
          "source",
        ],
        placeholder: "naver_place | 1000 | 70 | 9 | 24 | 6 | 4.6 | manual",
      },
      {
        key: "profile_score",
        label: "프로필 완성도(0~100 · 선택)",
        type: "number",
      },
      {
        key: "owner_note",
        label: "사장님 메모(선택)",
        type: "textarea",
      },
    ],
  },
  {
    code: "academy-review",
    name: "리뷰 답글 담당",
    description:
      "손님 리뷰를 읽고 매장 말투로 답글 초안 1개와 대안 2개를 씁니다.",
    group: "학원 특화",
    priority: false,
    available: true,
    fields: [
      {
        key: "raw_paste",
        label: "리뷰 붙여넣기 (여러 건도 됩니다)",
        type: "textarea",
        placeholder:
          "★★★★☆ 김서연 — 사진 예쁘게 나왔어요. 대기 시간이 조금 길었어요.",
      },
      {
        key: "review.rating",
        label: "별점(1~5)",
        type: "number",
      },
      {
        key: "review.text",
        label: "리뷰 본문",
        type: "textarea",
        placeholder: "친절하게 잘 봐주셨어요",
      },
      {
        key: "review.author",
        label: "작성자",
        type: "text",
        placeholder: "김서연",
      },
      {
        key: "channel",
        label: "리뷰가 올라온 곳",
        type: "select",
        options: ["naver", "kakao", "google", "website"],
      },
      {
        key: "tone_override",
        label: "말투(선택)",
        type: "select",
        options: ["formal", "friendly", "plain"],
      },
    ],
  },
  {
    code: "CORE-01",
    name: "예약 접수·확정·변경",
    description:
      "고객이 예약을 요청하면 시간이 비어 있으면 확정하고, 이미 찼으면 다른 시간을 제안합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "customer_name",
        label: "customer name",
        type: "text",
      },
      {
        key: "service",
        label: "service",
        type: "text",
      },
      {
        key: "requested_datetime",
        label: "requested datetime",
        type: "text",
        required: true,
      },
    ],
  },
  {
    code: "CORE-02",
    name: "노쇼·당일 리마인더",
    description: "노쇼를 줄이기 위한 당일 리마인더 메시지 템플릿을 작성합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "as_of",
        label: "as of",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-03",
    name: "신규 고객 상담 챗봇",
    description: "처음 방문하는 고객의 질문(가격·시간·예약)에 답합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "question",
        label: "question",
        type: "text",
        required: true,
      },
      {
        key: "customer_name",
        label: "customer name",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-04",
    name: "24시간 자동응답 챗봇",
    description:
      "영업시간 외 자동응답. 매장 정보로 답하고 모르는 건 추측하지 않습니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "question",
        label: "question",
        type: "text",
        required: true,
      },
    ],
  },
  {
    code: "CORE-05",
    name: "카카오·문자 마케팅 발송",
    description:
      "캠페인용 카카오·문자 홍보 메시지와 A/B 대체안 2개를 작성합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "topic",
        label: "topic",
        type: "text",
        required: true,
      },
      {
        key: "offer",
        label: "offer",
        type: "text",
      },
      {
        key: "target",
        label: "target",
        type: "text",
      },
      {
        key: "channel",
        label: "channel",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-07",
    name: "리뷰 수집 & 자동응답",
    description:
      "고객 리뷰에 대한 답변 초안을 작성합니다(진정성 있게, 과한 약속 없이).",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "review_text",
        label: "review text",
        type: "textarea",
        required: true,
      },
      {
        key: "rating",
        label: "rating",
        type: "number",
      },
      {
        key: "platform",
        label: "platform",
        type: "text",
      },
      {
        key: "author",
        label: "author",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-08",
    name: "인스타그램·SNS 콘텐츠 생성",
    description:
      "매장·작업 사진으로 인스타그램·블로그·카카오 콘텐츠를 생성합니다(샘플 사진 없음).",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "image",
        label: "image",
        type: "text",
        required: true,
      },
      {
        key: "tone",
        label: "tone",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-09",
    name: "결제·환불·정산",
    description:
      "카드 매출·수수료·환불을 합산해 정산 요약(정산 예정액)을 만듭니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "period",
        label: "period",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-10",
    name: "매출·운영 리포트",
    description: "매출 데이터를 핵심 지표가 담긴 리포트로 정리합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "period",
        label: "period",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-11",
    name: "재방문 캠페인",
    description: "한동안 안 온 단골에게 보낼 재방문 유도 메시지를 작성합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "segment",
        label: "segment",
        type: "text",
        required: true,
      },
      {
        key: "incentive",
        label: "incentive",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-12",
    name: "휴면·이탈 고객 감지",
    description: "휴면 기준을 넘겨 방문이 없는 고객을 추려냅니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "as_of",
        label: "as of",
        type: "text",
        required: true,
      },
      {
        key: "dormant_days",
        label: "dormant days",
        type: "number",
      },
    ],
  },
  {
    code: "CORE-13",
    name: "멤버십·이용권 설계",
    description: "메뉴 가격을 기반으로 멤버십·이용권 상품을 설계합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "goal",
        label: "goal",
        type: "text",
        required: true,
      },
      {
        key: "constraints",
        label: "constraints",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-14",
    name: "추천 리워드 프로그램",
    description: "추천 규정에 따라 발급할 추천 리워드 초안을 작성합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "referrer",
        label: "referrer",
        type: "text",
      },
      {
        key: "referee",
        label: "referee",
        type: "text",
      },
      {
        key: "milestone",
        label: "milestone",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-15",
    name: "직원 스케줄·근태",
    description: "각 직원의 가능 요일을 지켜 주간 근무표를 작성합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "week_of",
        label: "week of",
        type: "text",
      },
      {
        key: "constraints",
        label: "constraints",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-16",
    name: "재고·발주 알림",
    description: "재주문 기준 이하로 떨어진 재고 품목을 표시합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "as_of",
        label: "as of",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-18",
    name: "위생·시설 체크리스트",
    description: "매장 위생·시설 점검 체크리스트를 생성합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "scope",
        label: "scope",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-19",
    name: "만족도 설문 수집",
    description: "서비스 이용 후 만족도 설문을 작성합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "purpose",
        label: "purpose",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-21",
    name: "셀프 예약·변경",
    description:
      "고객이 직접 예약합니다. 빈 시간이면 확정, 아니면 대안을 제시합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "service",
        label: "service",
        type: "text",
      },
      {
        key: "requested_datetime",
        label: "requested datetime",
        type: "text",
        required: true,
      },
      {
        key: "change_of",
        label: "change of",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-22",
    name: "영업시간·시간표 안내",
    description:
      "영업시간·시간표 질문에 답하고, 실시간 예약 가능 여부는 예약 링크로 안내합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "question",
        label: "question",
        type: "text",
        required: true,
      },
    ],
  },
  {
    code: "CORE-23",
    name: "이용권 잔여 횟수",
    description: "고객의 이용권 잔여 횟수와 만료일을 알려줍니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "question",
        label: "question",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-24",
    name: "서비스 이용 이력",
    description: "고객의 과거 방문 이력을 최신순으로 보여줍니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "customer_name",
        label: "customer name",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-25",
    name: "프로모션·쿠폰 추천",
    description: "등록된 혜택 중에서 고객에게 맞는 프로모션을 골라줍니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "offers",
        label: "offers",
        type: "taglist",
        required: true,
      },
    ],
  },
  {
    code: "CORE-26",
    name: "만족도 피드백",
    description: "고객 피드백에 대한 따뜻한 답변 초안을 작성합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "rating",
        label: "rating",
        type: "number",
      },
      {
        key: "notes",
        label: "notes",
        type: "textarea",
      },
    ],
  },
  {
    code: "CORE-27",
    name: "적립 포인트 잔액",
    description: "고객의 적립 포인트 잔액과 사용 가치를 알려줍니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "question",
        label: "question",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-28",
    name: "서비스 Q&A",
    description: "서비스 관련 질문(종류·가격·옵션 등)에 답합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "question",
        label: "question",
        type: "text",
        required: true,
      },
    ],
  },
  {
    code: "CORE-29",
    name: "동반·단체 예약",
    description:
      "인원이 수용 범위 안이고 시간이 비어 있으면 단체 예약을 확정합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "service",
        label: "service",
        type: "text",
      },
      {
        key: "party_size",
        label: "party size",
        type: "number",
        required: true,
      },
      {
        key: "requested_datetime",
        label: "requested datetime",
        type: "text",
        required: true,
      },
    ],
  },
  {
    code: "CORE-30",
    name: "다음 방문·재등록 안내",
    description:
      "고객의 이용권 정보를 활용해 재방문·재등록을 유도하는 메시지를 작성합니다.",
    group: "공통 업무",
    priority: false,
    available: true,
    fields: [
      {
        key: "reason",
        label: "reason",
        type: "text",
      },
    ],
  },
  {
    code: "CORE-17",
    name: "경쟁사 모니터링",
    group: "추가 검토",
    description: "학원 용어·근거·출력 재설계 필요",
    priority: false,
    available: false,
    fields: [],
  },
  {
    code: "CORE-20",
    name: "세무·영수증 정리",
    group: "추가 검토",
    description: "학원 용어·근거·출력 재설계 필요",
    priority: false,
    available: false,
    fields: [],
  },
  {
    code: "CORE-TREND",
    name: "트렌드 추천",
    group: "추가 검토",
    description: "학원 용어·근거·출력 재설계 필요",
    priority: false,
    available: false,
    fields: [],
  },
  {
    code: "CORE-31",
    name: "홈페이지 담당",
    group: "추가 검토",
    description: "학원 데이터 연결 필요",
    priority: false,
    available: false,
    fields: [],
  },
  {
    code: "CORE-32",
    name: "단골 담당",
    group: "추가 검토",
    description: "학원 데이터 연결 필요",
    priority: false,
    available: false,
    fields: [],
  },
  {
    code: "CORE-33",
    name: "배포 담당",
    group: "추가 검토",
    description: "학원 데이터 연결 필요",
    priority: false,
    available: false,
    fields: [],
  },
  {
    code: "CORE-34",
    name: "정보 동기화 담당",
    group: "추가 검토",
    description: "학원 데이터 연결 필요",
    priority: false,
    available: false,
    fields: [],
  },
  {
    code: "CORE-35",
    name: "사진 촬영 기획",
    group: "추가 검토",
    description: "학원 데이터 연결 필요",
    priority: false,
    available: false,
    fields: [],
  },
];
